CC:= g++
FLAGS:= -pthread -std=c++11

compile:
	$(CC) SSOOIIGLE.cpp -o SSOOIIGLE $(FLAGS)

run:
	./SSOOIIGLE Libros/17\ LEYES\ DEL\ TRABAJO\ EN\ EQUIPO.txt equipo 4 

test:
	./SSOOIIGLE prueba.txt hola 3 	

clean:
	rm SSOOIIGLE